version: "3.7"

services:
    airport-ms:
        image: airport-ms
        ports:
            - "4000:4000" 
        depends_on:
            - db 
            - redis
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airports?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
    db:
        image: mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: airports
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    redis:
        image: "redis:alpine"
        command: redis-server --requirepass root
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/var/lib/redis
volumes:
    db-data:
    redis-data: